theme: fullwidth
min_acl: internal
undocumented_text: ""

output: "./docs"
readme: "**/README.md"

exclude:
    - "./SwiftExtensions/Sample\ App/*"

custom_categories:
  - name: UI Elements
    children:
    - SETextField
    - SEButton
    - SEPrimaryButton
    - SESecondaryButton
    - SETertiaryButton
    - SEQuaternaryButton

  - name: UIKit
    children:
    - UIApplication
    - UIColor
    - UITextField
    - UIView
    - UIViewController
    - UIViewDesignable
    - UIViewGradient

  - name: SEHelpers
    children:
    - SEAnimation
    - SEDebug
    - SEKeyboardManager

  - name: Foundation
    children:
    - Date
